name: Test App
on:
  push:
    branches: 
      - master
    

jobs:
  build-app:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [18.0]

    steps:
      - name: check out the code 
        uses: actions/checkout@v4.2.2

      - name: setup node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: node-version
          

      - name: Install App Packages
        run: | 
          npm install 
          pwd


      - name: run the app 
        run: npm start
